name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature']
  - title: '🐛 Fixes'
    labels: ['bug', 'fix']
  - title: '🛠 Improvements'
    labels: ['enhancement', 'chore']
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## Changes
  $CHANGES

  ## 🚀 APK
  👉 Download from the assets below ⬇️
