name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # ✅ Setup JDK 17 (needed for Gradle & Android)
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # ✅ Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # ✅ Generate local.properties so Gradle finds SDK
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      # ✅ Build debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug
