name: Build & Release Debug APK

on:
  workflow_dispatch: # allows manual trigger
  push:
    branches:
      - main # or master, depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
